version: "3.8"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/db:/app/db
    ports:
      - "${PORT_BACKEND}:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

  frontend:
    build:
      context: ./ui
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
